version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: "blog"
    ports:
      - "5432:5432"
    volumes:
      - ./create-script.sql:/docker-entrypoint-initdb.d/create-script.sql
      - ./insert-mock.sql:/docker-entrypoint-initdb.d/insert-mock.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 1111:8080